var test2 = 1
throw Error("stack shows error from original source")
